import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { blogPosts, getPostBySlug, type BlogSection } from '../data/blogPosts';

function formatDate(iso: string) { return new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }); }
function Section({ section }: { section: BlogSection }) {
  if (section.type === 'heading') return <h2 className="font-display mt-9 text-2xl font-bold text-[#1A1A1A] sm:text-[26px]">{section.text}</h2>;
  if (section.type === 'paragraph') return <p className="mt-4 text-[15px] leading-7 text-[#4A4842] sm:text-base sm:leading-8">{section.text}</p>;
  if (section.type === 'list') return <ul className="mt-4 space-y-2.5">{section.items.map((item, i) => <li key={i} className="flex gap-3 text-[15px] leading-7 text-[#4A4842] sm:text-base"><span className="mt-2.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#1D9E75]" /><span>{item}</span></li>)}</ul>;
  return <blockquote className="mt-6 rounded-2xl border-l-4 border-[#1D9E75] bg-[#F0FAF6] px-5 py-4 text-[15px] font-medium italic leading-7 text-[#0D3028] sm:text-base">{section.text}</blockquote>;
}

export default function BlogPost() {
  const { slug } = useParams<{ slug: string }>();
  const post = slug ? getPostBySlug(slug) : undefined;
  useEffect(() => { if (post) document.title = `${post.title} | RoleWave Blog`; }, [post]);
  if (!post) return <div className="page-shell"><div className="mx-auto flex w-full max-w-[720px] flex-col items-center px-4 py-24 text-center"><p className="text-[10px] font-bold uppercase tracking-[1.7px] text-[#1D9E75]">RoleWave blog</p><h1 className="font-display mt-3 text-3xl font-bold text-[#1A1A1A]">We couldn't find that article</h1><p className="mt-3 text-sm text-[#6B6960]">It may have moved, or the link might be out of date.</p><Link to="/blog" className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#0D3028] px-5 py-2.5 text-sm font-bold text-white"><ArrowLeft size={15} /> Back to all articles</Link></div></div>;
  const Icon = post.icon; const related = blogPosts.filter((item) => item.slug !== post.slug).slice(0, 2);
  return <div className="page-shell"><div className="mx-auto w-full max-w-[760px] px-4 pb-16 pt-6 sm:px-6"><Link to="/blog" className="inline-flex items-center gap-1.5 text-sm font-semibold text-[#085041]"><ArrowLeft size={15} /> Back to career resources</Link><div className="mt-6 flex h-11 w-11 items-center justify-center rounded-2xl bg-[#E1F5EE] text-[#085041]"><Icon size={19} /></div><p className="mt-5 text-[10px] font-bold uppercase tracking-[1.7px] text-[#1D9E75]">{post.category}</p><h1 className="font-display mt-2 text-[32px] font-bold leading-[1.08] tracking-[-0.6px] text-[#1A1A1A] sm:text-[44px]">{post.title}</h1><div className="mt-4 text-sm text-[#6B6960]"><span>{formatDate(post.publishedAt)}</span></div><article className="mt-2 border-t border-[#E5E1D8] pt-6">{post.content.map((section, i) => <Section key={i} section={section} />)}</article><div className="mt-10 flex flex-col items-start gap-4 rounded-[28px] px-6 py-7 text-white sm:flex-row sm:items-center sm:justify-between" style={{ background: 'linear-gradient(135deg, #0D3028 0%, #12684F 58%, #1D9E75 100%)' }}><p className="text-base font-semibold leading-6 sm:max-w-xs">{post.category === 'For employers' ? 'Ready to find your next hire?' : 'Ready to put this into practice?'}</p><Link to={post.ctaHref} className="inline-flex shrink-0 items-center gap-2 rounded-full bg-white px-5 py-2.5 text-sm font-bold text-[#0D3028]">{post.ctaLabel} <ArrowUpRight size={15} /></Link></div><div className="mt-12"><p className="text-[10px] font-bold uppercase tracking-[1.7px] text-[#1D9E75]">More from the blog</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{related.map((item) => { const RelatedIcon = item.icon; return <Link key={item.slug} to={`/blog/${item.slug}`} className="rounded-2xl border border-[#E5E1D8] bg-[#FBFAF7]/80 p-5"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#E1F5EE] text-[#085041]"><RelatedIcon size={16} /></div><h3 className="mt-4 text-base font-bold text-[#1A1A1A]">{item.title}</h3><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#085041]">Read article <ArrowUpRight size={12} /></span></Link>; })}</div></div></div></div>;
}
